import { Product } from '../product.model';

export const necklaces: Product[] = [
    {
      id: 101,
      name: 'Classic Pearl Necklace',
      image: 'assets/necklaces/necklace1.jpg',
      alt: 'Elegant classic pearl necklace',
      price: 150,
      description: 'A timeless pearl necklace for all occasions.',
      category: 'necklaces',
      metal: 'Gold plated',
      size: ['one size'],
      sold: 200,
      dateAdded: '2023-12-05',
    },
    {
      id: 102,
      name: 'Gold Chain Necklace',
      image: 'assets/necklaces/necklace2.jpg',
      alt: 'Bold gold chain necklace with modern design',
      price: 200,
      description: 'A bold gold chain necklace with a contemporary style.',
      category: 'necklaces',
      metal: 'Gold plated',
      size: ['one size'],
      sold: 350,
      dateAdded: '2023-11-30',
    },
    {
      id: 103,
      name: 'Diamond Pendant Necklace',
      image: 'assets/necklaces/necklace3.jpg',
      alt: 'Luxury diamond pendant necklace',
      price: 500,
      description: 'A luxurious diamond pendant necklace for special moments.',
      category: 'necklaces',
      metal: 'Gold plated',
      size: ['one size'],
      sold: 50,
      dateAdded: '2023-10-10',
    },
    {
      id: 104,
      name: 'Custom Name Necklace',
      image: 'assets/necklaces/necklace4.jpg',
      alt: 'Stylish custom name necklace',
      price: 100,
      description: 'A stylish name necklace, perfect for personalized gifts.',
      category: 'necklaces',
      metal: 'Gold plated',
      size: ['one size'],
      sold: 400,
      dateAdded: '2023-09-15',
    },
    {
      id: 105,
      name: 'Minimalist Bar Necklace',
      image: 'assets/necklaces/necklace5.jpg',
      alt: 'Simple minimalist bar necklace',
      price: 75,
      description: 'A simple and minimalist necklace with a bar design.',
      category: 'necklaces',
      metal: 'Gold plated',
      size: ['one size'],
      sold: 300,
      dateAdded: '2023-08-01',
    },
    {
        id: 105,
        name: 'Minimalist Bar Necklace',
        image: 'assets/necklaces/necklace6.jpg',
        alt: 'Simple minimalist bar necklace',
        price: 75,
        description: 'A simple and minimalist necklace with a bar design.',
        category: 'necklaces',
        metal: 'Gold plated',
        size: ['one size'],
        sold: 300,
        dateAdded: '2023-08-01',
      },
      {
        id: 105,
        name: 'Minimalist Bar Necklace',
        image: 'assets/necklaces/necklace7.jpg',
        alt: 'Simple minimalist bar necklace',
        price: 75,
        description: 'A simple and minimalist necklace with a bar design.',
        category: 'necklaces',
        metal: 'Gold plated',
        size: ['one size'],
        sold: 300,
        dateAdded: '2023-08-01',
      },
      {
        id: 105,
        name: 'Minimalist Bar Necklace',
        image: 'assets/necklaces/necklace8.jpg',
        alt: 'Simple minimalist bar necklace',
        price: 75,
        description: 'A simple and minimalist necklace with a bar design.',
        category: 'necklaces',
        metal: 'Gold plated',
        size: ['one size'],
        sold: 300,
        dateAdded: '2023-08-01',
      },
      {
        id: 105,
        name: 'Minimalist Bar Necklace',
        image: 'assets/necklaces/necklace9.jpg',
        alt: 'Simple minimalist bar necklace',
        price: 75,
        description: 'A simple and minimalist necklace with a bar design.',
        category: 'necklaces',
        metal: 'Gold plated',
        size: ['one size'],
        sold: 300,
        dateAdded: '2023-08-01',
      },
      {
        id: 105,
        name: 'Minimalist Bar Necklace',
        image: 'assets/necklaces/necklace10.jpg',
        alt: 'Simple minimalist bar necklace',
        price: 75,
        description: 'A simple and minimalist necklace with a bar design.',
        category: 'necklaces',
        metal: 'Gold plated',
        size: ['one size'],
        sold: 300,
        dateAdded: '2023-08-01',
      },
      {
        id: 105,
        name: 'Minimalist Bar Necklace',
        image: 'assets/necklaces/necklace11.jpg',
        alt: 'Simple minimalist bar necklace',
        price: 75,
        description: 'A simple and minimalist necklace with a bar design.',
        category: 'necklaces',
        metal: 'Gold plated',
        size: ['one size'],
        sold: 300,
        dateAdded: '2023-08-01',
      },
  ];
  