import { Product } from './product.model';

export const products: Product[] = [
  {
    id: 1,
    name: 'Encircled Clasp Bangle',
    image: 'assets/bracelets/bracelets9.jpg',
    price: 100,
    description: 'A beautiful clasp bangle for all occasions.',
    category: 'bracelets',
    size: ['small', 'medium', 'large'],
    sold: 150,
    dateAdded: '2023-12-01',
  },
  {
    id: 2,
    name: 'Happy Birthday To You Charm Bracelet Set',
    image: 'assets/bracelets/bracelets15.jpg',
    price: 75,
    description: 'Celebrate birthdays in style with this charm bracelet set.',
    category: 'bracelets',
    size: ['one size'],
    sold: 250,
    dateAdded: '2023-11-20',
  },
  {
    id: 3,
    name: 'Heart Clasp Snake Chain Bracelet',
    image: '../assets/bracelets/braceletsIII.jpg',
    price: 250,
    description: 'A premium snake chain bracelet with heart clasp.',
    category: 'bracelets',
    size: ['medium', 'large'],
    sold: 100,
    dateAdded: '2023-10-15',
  },
  {
    id: 4,
    name: 'Engravable Heart Clasp Snake Chain Bracelet',
    image: '../assets/bracelets/bracelets12.jpg',
    price: 120,
    description: 'A stylish bracelet with an engravable heart clasp.',
    category: 'bracelets',
    size: ['small', 'medium'],
    sold: 180,
    dateAdded: '2023-09-28',
  },
  {
    id: 5,
    name: 'Snake Chain Slider Bracelet',
    image: '../assets/bracelets/bracelets14.jpg',
    price: 75,
    description: 'An adjustable snake chain bracelet for a custom fit.',
    category: 'bracelets',
    size: ['one size'],
    sold: 300,
    dateAdded: '2023-08-05',
  },
  {
    id: 6,
    name: 'Heart & Butterfly Bracelet Set',
    image: '../assets/bracelets/bracelets17.jpg',
    price: 75,
    description: 'A charming bracelet set featuring heart and butterfly designs.',
    category: 'bracelets',
    size: ['small', 'medium'],
    sold: 500,
    dateAdded: '2023-06-01',
  },
  {
    id: 7,
    name: 'Pavé Cuban Chain Bracelet',
    image: '../assets/bracelets/bracelets8.jpg',
    price: 75,
    description: 'A bold Cuban chain bracelet adorned with pavé details.',
    category: 'bracelets',
    size: ['medium', 'large'],
    sold: 400,
    dateAdded: '2023-07-20',
  },
  {
    id: 8,
    name: 'Sparkling Tennis Bracelet',
    image: '../assets/bracelets/bracelets10.jpg',
    price: 120,
    description: 'A sparkling tennis bracelet perfect for any event.',
    category: 'bracelets',
    size: ['small', 'medium'],
    sold: 300,
    dateAdded: '2023-05-15',
  },
  {
    id: 9,
    name: 'Barrel Clasp Snake Chain Bracelet',
    image: 'assets/bracelets/bracelets11.jpg',
    price: 75,
    description: 'A classic snake chain bracelet with a barrel clasp.',
    category: 'bracelets',
    size: ['small', 'medium'],
    sold: 150,
    dateAdded: '2023-04-10',
  },
  {
    id: 10,
    name: 'Barbed Wire Heart Bracelet Set',
    image: 'assets/bracelets/bracelets19.jpg',
    price: 110,
    description: 'A unique barbed wire bracelet with a heart centerpiece.',
    category: 'bracelets',
    size: ['medium'],
    sold: 50,
    dateAdded: '2023-03-18',
  },
  // Add more products as needed
  {
    id: 20,
    name: 'Heart T-Bar Snake Chain Bracelet',
    image: 'assets/bracelets/bracelets23.jpg',
    price: 85,
    description: 'A versatile bracelet with a heart T-bar clasp.',
    category: 'bracelets',
    size: ['medium', 'large'],
    sold: 100,
    dateAdded: '2024-01-10',
  }
];
